### ISSUE TITLE
open Sexplib inside an Inez script leads to unbound module error

### ISSUE THREAD

**Issue by minmit** [vasilisp/inez#1]
Hi, 

Is there a way to use Sexplib inside an Inez script? The following leads to an error "unbound module Sexplib" when running with ./inez.opt, but is find when built with ocaml separately. 

open Script;;
open Sexplib;;

Thanks!

**Comment by vasilisp** [comment]
I am afraid you need to compile a few `sexplib` files into `inez.opt`. This requires a small modification of the build system (8f17478fa7f6d5df70e3b1c3e3c84667f69c9a47), which I just pushed to the `sexplib-script` branch.

**Comment by minmit** [comment]
Great, thanks! It is working now. Does using other libraries require similar changes to the build?

**Comment by vasilisp** [comment]
You are welcome!

Yes, you would need to do the same thing, pretty much. The `cmi` part applies for regular libraries, and the `cmxs` part for Camlp4 plugins that extend the OCaml syntax (`sexplib` requires both parts)

**Comment by minmit** [comment]
Great, thank a lot!
