### ISSUE TITLE
Unbound constructor Type.Y_Int_Arrow when used with Sexplib

### ISSUE THREAD

**Issue by minmit** [vasilisp/inez#2]
Hi,

On branch sexplib-script, the following causes an "Unbound constructor Type.Y_Int_Arrow":

open Sexplib;;
let loc (n : Int) = ~free;;

But if Sexplib is opened after the function definition, it works without any errors. Is there a conflict between Sexplib and Script?

Thanks!

**Comment by vasilisp** [comment]
Hi,

`Inez` has a `Type` module which is used internally to implement uninterpreted functions. Apparently, there is also a `Sexplib.Type` module. If you open `Sexplib`, its `Type` comes into scope and conflicts with ours.

I would suggest using `Sexplib` without opening it. Just say `Sexplib.foo` for any `foo` of interest, or if you really want something shorter, just define `module S = Sexplib` and subsequently refer to `S.foo`.

**Comment by minmit** [comment]
Problem solved, thanks!
